#!/bin/sh

echo "Removing python files"
rm "/usr/bin/spicegui"
rm "/usr/lib/python2.7/site-packages/spicegui-0.1-py2.7.egg"

echo "Removing desktop file"
rm "/usr/share/applications/SpiceGUI.desktop"
update-desktop-database

echo "Unsetting schemas"
rm "/usr/share/glib-2.0/schemas/org.rafael1193.spicegui.gschema.xml"
glib-compile-schemas /usr/share/glib-2.0/schemas/

echo "Installing syntax highlightning definitions"
rm "/usr/share/gtksourceview-3.0/spice-netlist.lang"

echo "Removing glade files"
rm -r "/usr/share/spicegui"
